### ISSUE TITLE
Encryption not available on this event-machine

### ISSUE THREAD

**Issue by Kavi6** [ably/ably-ruby#109] opened 2017-01-12 05:49 UTC
terminate called after throwing an instance of 'std::runtime_error'
  what():  Encryption not available on this event-machine

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

tried all possible command.. still getting the same error..

**Comment by mattheworiordan** [comment] 2017-01-12 10:35
Duplicate of https://github.com/ably/ably-ruby/issues/92

**Closed by mattheworiordan** 2017-01-12 10:35 UTC
Labels: duplicate
